application: pytaku
version: 0-8
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
  # GAE default. Don't touch!
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
  # Custom rules go here
- ^frontend$  # ignore "frontend" dir (we use frontend-dist for deployment)
- ^node_modules$  # hell no
- ^bower_components$  # nope
- ^bower\.json$
- ^Gulpfile\.js$
- ^package\.json$
- ^requirements\.txt$

handlers:
- url: /static
  static_dir: frontend-dist/static
  secure: always

- url: /favicon\.ico
  static_files: frontend-dist/favicon.ico
  upload: frontend-dist/favicon\.ico

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
