#!/usr/bin/env bash

# Add Google App Engine SDK path and project home dir to $PYTHONPATH.
# This helps with Jedi suggestions.
export PYTHONPATH="$PYTHONPATH:$GAE_PATH:`pwd`"

# Build frontend assets + deploy to google app engine
function deploy {
    if [[ $1 == "prod" ]]; then
        echo 'Deploying to production server: pytaku.appspot.com...'
        gulp deploy && python $GAE_PATH/appcfg.py --oauth2 update .
    else
        echo 'Deploying to dev server: pytaku-dev.appspot.com...'
        gulp deploy && python $GAE_PATH/appcfg.py \
            --oauth2 \
            --application='pytaku-dev' \
            update .
    fi
}
