#!/usr/bin/env bash

# Add Google App Engine SDK path and project home dir to $PYTHONPATH.
# This helps with Jedi suggestions.
export PYTHONPATH="$PYTHONPATH:$GAE_PATH:`pwd`"

# Build frontend assets + deploy to google app engine
alias deploy="gulp deploy && python $GAE_PATH/appcfg.py --oauth2 update ."
