#!/usr/bin/env bash

# Add Google App Engine SDK path and project home dir to $PYTHONPATH.
# This helps with Jedi suggestions.
export PYTHONPATH="$PYTHONPATH:$GAE_PATH:`pwd`"

# Build frontend assets + deploy to google app engine
function deploy {
    if [[ -z "$1" ]]; then
        project='pytaku-dev'
    else
        project=$1
    fi

    echo "Deploying to ${project}.appspot.com..."
    gulp deploy && python $GAE_PATH/appcfg.py \
        --oauth2 \
        --application="$project" \
        update .
}
